### ISSUE TITLE
Strange select overflow causing horizontal scroll on fullhd res

### ISSUE THREAD

**Issue by entr** [wp-papi/papi#105]
This is WP 4.0.8, papi [#8409cfa](https://github.com/wp-papi/papi/commit/8409cfa0710908ff3d2fdbe1bc962d806f3f10a7) on Google Chrome 45.0.2454.93 (LinuxMint). I can see the select excessive width on firefox too but without the horizontal scroll.

```position: relative; ``` on the direct parent element seems to "fix" it.

![papi-select-width](https://cloud.githubusercontent.com/assets/191571/10708564/03d9840e-7a16-11e5-8741-88fec23ac475.jpg)

Do you need additional info?

**Comment by frozzare** [comment]
It's the dropdown a select2 dropdown? It's looks like that and then it maybe a issue with select2 css and wps css that don't place nice. I do get a bit of overflow when I use select2 but not as much as you do. Since I don't have a LinuxMint with Chrome can you dig some more and try to figure out which css is casing this?
