### ISSUE TITLE
Repeater - Custom "add" label

### ISSUE THREAD

**Issue by nlemoine** [wp-papi/papi#106]
Hi, 

Would you consider the possibility of customizing the "add row" button label? So labels can reflect the item being repeated: "Add new slide", etc. 

I can work on a PR if needed.

**Comment by frozzare** [comment]
This would be nice to have on a flexible too, e.g `Add new module` or something like that. Would be best if this is added as settings on both properties and the default value should be the existing label. If you like you can do PR otherwise I can fix this tonight, will try to release 2.4.2 tomorrow.

**Comment by nlemoine** [comment]
I'll let you fix this if you don't mind, you'll probably do this faster than I will. 

I will fix another issue I noticed meanwhile.

**Comment by nlemoine** [comment]
Thanks!
