### ISSUE TITLE
Page id conflict

### ISSUE THREAD

**Issue by nlemoine** [wp-papi/papi#107]
I'm having an issue with page ids. 

My "types" are located in multiple directories, registered with the `papi/settings/directories` filter. Two files have the same name and this causes a conflict in admin menu (I'm using option types). 

The file name is used to assign the page id. If multiple directories can be registered, I think the file name is not a strong enough value to ensure a unique id.

**Comment by nlemoine** [comment]
Probably by taking the full path of the file? Or relative path from project root.

**Comment by frozzare** [comment]
Hm, you're right. It's not uniqued enough. Adding one level up will not solve it since you can have to directories that have the same name that you have register, e.g `path1/page-types` and `path2/page-types`.

I don't think adding the full path is a good since you can have very long paths that may case errors in the browser since the path can be too long.

Relative path from project root, what project root? Plugin root or theme root or `ABSPATH`?

**Comment by frozzare** [comment]
One problem by adding a longer `id` is that all queries and stuff you doing between types and needs to be longer when you re save the page since they are having a longer `id` in the database.

For example:

`'meta_value' => 'modules/feature-type'`
vs

`'meta_value' => 'wp-content/themes/papi-theme/lib/page-types/modules/feature-module-type'`

**Comment by frozzare** [comment]
Maybe you this already but you can set a custom `id` in `page_type` method to whatever you want.

**Comment by nlemoine** [comment]
> I don't think adding the full path is a good since you can have very long paths that may case errors in the browser since the path can be too long.

I don't think the URL max lentgh would be an issue. But sure this would be ugly. A truncated md5 of that path?

> Relative path from project root, what project root? Plugin root or theme root or ABSPATH?

I thought relative to `ABSPATH` or webroot. 

> Maybe you this already but you can set a custom id in page_type method to whatever you want.

Thanks for the tip, that's what I did for now ;)

**Comment by frozzare** [comment]
Maybe the length of the query strings isn't a issue but when querying posts with `WP_Query` when you need to write a long path instead of a short one will be a issue. So a long path isn't good for that.

I will not do anything about this now since it affect more that just the id and don't is a big issue since you can solve it with the id value.

**Comment by frozzare** [comment]
I talked a bit with @rasmusbe about this and we think the best to avoid this is the use the latest page type when two page types has the same id and update the documentation about that this can happen and you can change the name or change the id of the page type.

**Comment by frozzare** [comment]
@rasmusbe can you take a look at this? https://github.com/wp-papi/papi/commit/70cd6499dd50da3c39cf199dbf9a3fc3d092246b it will solve the issue with two or more page types with same id, it will take the last page type with the same id.

**Comment by frozzare** [comment]
I have merged https://github.com/wp-papi/papi/tree/issue-107 to master now.

It will work like this:

1. If you have 2 classes with exact class name (with same namespace or without) only the last class will be loaded and that can't `id` value in meta array solve since we can't load 2 classes with the same name.
2. If 2 classes with different class names but with same `id` value in meta array will load the last one.
