### ISSUE TITLE
What kind of actions and filters would you like to see in 3.0.0?

### ISSUE THREAD

**Issue by frozzare** [wp-papi/papi#122]
New actions:

New filters:
- `papi/admin/content_type_id`

**Comment by frozzare** [comment]
from @rasmusbe `papi/settings/column_hide_{$post_type}` and `papi/settings/column_title_{$post_type}` for hiding column and changing column title.

**Comment by entr** [comment]
Since there are quite a lot anonymously initiated classes, some of them could be exposed using `do_action('...', $this )`
In a quick search those seem to be promising candidates: `Papi_Admin_Menu`, `Papi_Admin_Assets`, `Papi_Admin_Ajax`. Another argument I can't help bringing up is the fact there are hooked methods in those classes that stay impossible(or really difficult) to remove.

**Comment by frozzare** [comment]
@entr anonymously hooks will not be changed. If you like to take Papi apart and remove assets, admin menus or something like that it's better to fork Papi.
