### ISSUE TITLE
File in specific destination

### ISSUE THREAD

**Issue by ekandreas** [wp-papi/papi#134]
This is a possible feature request)
I want to use "File" but don't want to store the value inside WordPress media library. Is it possible to store it in another (in my case protected) folder?

**Comment by rasmusbe** [comment]
My personal opinon is that the best practice is to use the WP Media Library, but if you really need an file upload outside of the WordPress file handling (and security) it should be written as an third party property.

**Comment by frozzare** [comment]
I agree, the file property is using the wordpress media library and it would require a lot of changes to create a media library that can handle protected files.

**Comment by ekandreas** [comment]
Ok, any hook or filter to manipulate the process?

**Comment by rasmusbe** [comment]
Since the property is using the WP Media Library I think you have to modify a lot to make it work. I think it's best to create a new property, make it output an `<input type="file">` and handle the file upload in the property with the prepare_value method ( I think that's the best method to use in the property, right @frozzare ? ).

**Comment by frozzare** [comment]
The media library has many filters and actions that you can use, and you could extend the file property (image and gallery does that). You can also look at the url property that can have a media uploader button.
