### ISSUE TITLE
Fields are cut in half on mobile

### ISSUE THREAD

**Issue by ekandreas** [wp-papi/papi#150]
When using WordPress wp-admin and edit a page type with Papi fields the fields are cut in half. Perhaps there are some responsive class missing to the inputs?

**Comment by frozzare** [comment]
I think you mean that the names are smaller since the fields are at 99.5% width. It's hard to adjust all fields to look good on a mobile phone, for example a flexible with different level of fields are a hard do adjust. I think it look good enough right now since we can't make the fields smaller, a lot of properties would break if we adjust the size right now. The most important is that you can type in a input field and you can, the property title get smaller but not the field.

**Comment by ekandreas** [comment]
Do as you want, the input fields are not adjusted as ordinary WordPress input fields.
Perhaps it should be written in the docs that Papi isn't responsive?
![img_1826](https://cloud.githubusercontent.com/assets/1794603/12921342/238526b4-cf4d-11e5-930a-11101023a877.PNG)
