### ISSUE TITLE
Double fields in option page

### ISSUE THREAD

**Issue by ekandreas** [wp-papi/papi#153]
### What I expected
I want single fields in option page only.

### What happened instead
I'm getting double fields in option page with Papi version 3.0.1.
The bug is eliminated to the scenario when calling "papi_get_option" in a anonymous function for hook init.
I have created a very small theme to reproduce it.
[papitest.zip](https://github.com/wp-papi/papi/files/136084/papitest.zip)

### Steps to reproduce
1. Activate the theme in WP
2. Go to "Appearance" in wp-admin.
3. The Option page is named "Settings".
4. The one and only prop is rendered twice.

### What versions of software are you using?
- Browser: Chrome latest
- Papi: 3.0.1

**Comment by ekandreas** [comment]
If I provide the get_papi_option with a post id 0 then everything looks fine.
Eg, 
```
add_action('init', function () {
    $profile_form = (int)papi_get_option(0,'profile_form');
});

**Comment by frozzare** [comment]
I think there is a problem with the boot functionality of all types.

`papi_get_option` can't take a post id parameter since there aren't any post id in the option table. You just changing the slug to 0 and the default value to `profile_form`. Look at the docs.

**Comment by ekandreas** [comment]
Yep, for me it is ok with a workaround.

**Comment by frozzare** [comment]
You shouldn't close a issue that is a real bug.

**Comment by frozzare** [comment]
This will be fixed in next patch release. https://github.com/wp-papi/papi/commit/2d1cae7993e9bb660180306a4fdba915e61c21b9

Due to the next merge box logic feature introduce in 3.0 (where you can have a base page type with boxes that will be merged with the child page type) the issue described here will do the same thing (merge boxes with itself) so the fix will reset boxes array when boxes isn't empty on `admin_init`.
