### ISSUE TITLE
PAPI in official WP pluigin repository

### ISSUE THREAD

**Issue by entr** [wp-papi/papi#174]
Have you considered putting PAPI in the official repo? That would be particularly useful when project is distributed as a theme. Then tool like [tgmpa](https://github.com/TGMPA/TGM-Plugin-Activation) can be used to effectively require dependencies, PAPI including.

**Comment by frozzare** [comment]
Yes I have, it will not be good since you can't do anything after installing the plugin unless you code. It's not a plug and play plugin.

You should also read this blog post by wp about framework/library plugins https://make.wordpress.org/plugins/2016/03/01/please-do-not-submit-frameworks/

Papi will stay on GitHub where you can download the releases and/or install it using composer.
