### ISSUE TITLE
Help request: Registering custom Taxonomy

### ISSUE THREAD

**Issue by twoSeats** [wp-papi/papi#228]
### What I expected
Created a Country_Taxonomy_Type & expected to see a registered Taxonomy with the custom Fields I had defined as properties.

### What happened instead
No Taxonomy present

I think there must be a step that I have missed. I managed to set up custom Post Types including custom fields and the multiple layout for Posts.
I can't find a step by step explanation of how to implement Taxonomy Features.

I have also created a file using the example Open_Taxonomy_Type & experienced the same result.

Is there an undocumented step that I'm missing?

### What versions of softwares are you using?

- Papi: ^3.1
- WordPress: 4.7.4

**Comment by frozzare** [comment]
Papi don't register custom post type or custom taxonomies, if you need to register a custom taxonomy I would recommend you to read this https://codex.wordpress.org/Function_Reference/register_taxonomy

**Comment by twoSeats** [comment]
Thanks, I did register some; but still didn't have the custom fields I registered using Papi available.
When I inspected the taxonomy data it seems the box data was empty... Not sure why this was the case.

![screenshot from 2017-05-02 16 41 51](https://cloud.githubusercontent.com/assets/536306/25622934/50d5a99e-2f56-11e7-8fb9-24ab0b1b577d.jpeg)

**Comment by frozzare** [comment]
Can you show the all content of the taxonomy type file? Just showing a images of the box/properties isn't show help full.

How taxonomy type works:
No custom fields are added to the "add new term" view since the layout of the page has both add new and a list, it's not so much space for advanced custom fields so we don't add any custom fields to the "add new term" view.

The custom fields are only showed in the "edit term view" where we can use a lot more space for proeprties, just like on the post page.

So you have to create a term and then add custom content to custom fields.

**Comment by twoSeats** [comment]
> "The custom fields are only showed in the "edit term view" where we can use a lot more space for properties, just like on the post page.
So you have to create a term and then add custom content to custom fields."

That actually clears up everything for me! I used the code exactly as in the examples in the documentation. My understanding was that the custom fields would be present even in the "add term view".

Thanks
