### ISSUE TITLE
All pages (new and existing) are being presented as newly created papi type

### ISSUE THREAD

**Issue by entr** [wp-papi/papi#235]
The moment I created a new page type class all my existing pages were shown as of this new type in the `edit.php?post_type=page` table. When I enable the standard type and I choose it from new page type selection page I am redirected to `post-new.php?page_type&post_type=page` and I'm seeing the properties of the custom papi type I created earlier. I've created only one papi type. Let me know if you need more data.

- Papi:  3.2.0-beta1
- WordPress: 4.7.5

**Comment by frozzare** [comment]
Please don't include the version in the title.

**Comment by frozzare** [comment]
Will take a look at it when I have some time to code on this project.

**Comment by frozzare** [comment]
I can't reproduce this, here is what I did:

1. Created a standard page that don't have any properties.
2. Created a article page that have 2 properties.
3. No article page properties is not showed on the standard page.
4. Article page properties is showed on the article page.

As you can see in the screenshot the post list don't indicate that they have the wrong page type.

![skarmklipp 2017-05-30 15 16 42](https://cloud.githubusercontent.com/assets/14610/26584975/0725c652-454b-11e7-8305-da19e8ea9514.png)

Could you try to reproduce this with the master branch? It's helpful if you have tested the master branch before you report any issues since maybe already fixed and if so it will save a lot of time.

**Comment by entr** [comment]
I'll test again and report back. Just keep it on-hold until after the following weekend. Thank you for looking into these!

**Comment by entr** [comment]
OK, I was able to reproduce again. What I did was:

1. Clean install WP 4.8
2. `$ wp plugin install --activate https://github.com/wp-papi/papi/archive/master.zip`
3. Scaffold a child-theme of `twentyseventeen` (`seventeen-child`)
4. Imported theme unit test XML: https://wpcom-themes.svn.automattic.com/demo/theme-unit-test-data.xml 
5. Created `seventeen-child/papi.php` where I placed the directory filter and required it from `seventeen-child/functions.php`

```php
<?php // seventeen-child/papi.php
add_filter( 'papi/settings/directories', function () {
  return __DIR__ . '/page-types';
} );
```
6. Just copy-pasted the `Video_Page_Type` from the [docs](http://wp-papi.github.io/docs/types/page.html) to
`twentyseventeen/page-types/class-custom-page-type.php`

When I visited `wp-admin/edit.php?post_type=page` I got this

![image](https://user-images.githubusercontent.com/191571/27001180-02e2020c-4dcc-11e7-8cbf-8e171f6be070.png)

Do I miss something?

**Comment by frozzare** [comment]
Sorry, The bug you reported isn't a bug since Papi don't enable WordPress "Standard Page" by default (if you have one Papi page type and don't enable standard page this behaviour is correct), you have to do that with a filter:

```
add_filter( 'papi/settings/show_standard_page_type_page', '__return_true' );
```

(where the last page word is the post type).

The bug that I found when finding this is that the column didn't respect the `show_standard_page_type` filter and that is what I will fix.

**Comment by entr** [comment]
OK, cool. Glad the report was useful after all.
