### ISSUE TITLE
Extend datetime property settings

### ISSUE THREAD

**Issue by sandralindberg** [wp-papi/papi#268]
I would suggestion 2 additional settings to the datetime property for a more flexible/user-friendly admin.

**Setting: Start day of week**
It would be neat if it was possible to change which day is the first day of the week, sun/mon. Currently it's Sunday but e.g. in Sweden we start our weeks on Monday. 

An alternative could be to set this based on installation locale

**Setting: Position of time**
It would be neat if it was possible to change the order of time-select/date-delect. For example positioning time before date or (as current layout) date before time. 

An alternative to having a setting for the position of time is to always have the time above the date OR to have a "Done"-button. Because atm the date-picker closes when a date is selected, which can cause an irritated user that forgot to change the time before selecting a date.

**Comment by frozzare** [comment]
**Setting: Start day of week**
You can use the `first_day` setting that exists in pikaday for this.

```
'settings' => [
  'first_day' => 1 // monday
]
```

**Setting: Position of time**
This isn't possible since we use a fork of pikaday with time and the [fork](https://github.com/owenmead/Pikaday) hasn't support for this, maybe it's something that we can do ourself.

**Comment by sandralindberg** [comment]
Ah, my bad that I didn't see the possibility too use pickaday settings.
