### ISSUE TITLE
Multiple images in repeater can't be added

### ISSUE THREAD

**Issue by Lindstromer** [wp-papi/papi#61]
If i create a repeater and try to upload an image to anything except for the first row the image will seem uploaded, but upon saving it will be lost.

Example screenshot on how it looks:
![screen shot 2015-05-06 at 22 55 09](https://cloud.githubusercontent.com/assets/1056004/7503393/fc8ca07c-f442-11e4-8644-6d9bbf0244e6.png)

Have checked the access/error-logs in nginx(running on bedrock-ansible stack) and there's no error output there. Also no error message in browser console or in wp-admin.

Tested in Chrome & Safari on latest OS X.

**Comment by frozzare** [comment]
Which version of Papi are you using?

**Comment by Lindstromer** [comment]
1.2.6.(Even though it says 1.3.0 in package.json, Composer says v1.2.6)

If I go back to 1.2.5 with composer it starts working so seems to be the latest version.

**Comment by frozzare** [comment]
That's strange. Works fine for me in 1.2.6 in VVV environment. The only changes in 1.2.6 had with query strings for the url builder in Papi.

Could you check what meta values (postmeta table) is saved on that post with the repeater slug?

The package.json version is a misstake, hard to fix in 1.2.6, the composer version is the right one.

**Comment by Lindstromer** [comment]
Strange, I've pulled out the meta values for that field in this gist:
https://gist.github.com/Lindstromer/f43f522ecb438b4df05b

I just wanted to be clear with the version thing, so that it wasn't me messing something up. :-)

**Comment by frozzare** [comment]
![skarmklipp 2015-05-07 10 38 16](https://cloud.githubusercontent.com/assets/14610/7511460/40f79d9a-f4a5-11e4-83c5-07e9e9f73bf6.png)

Looks like you are using master branch and not 1.2.6. Rows that ends in `_property` should just save a string value, for example `image`. The values you provided are wrong and 1.2.6 do not serialize values, 1.3.0 (master branch, unsafe) will serialize the property so it *could* be saved in the database but isn't since the property type value is the only thing needed in the database.

Could you try to download 1.2.6 direct from the [release](https://github.com/wp-papi/papi/releases/tag/v1.2.6) and try to create a new page so you don't have any old values?

**Comment by Lindstromer** [comment]
Really strange, if i set 1.2.6 in composer it says it's already installed/nothing updated upon running composer update. So I guess it shouldn't be running on master branch.

I downloaded directly from the release(even tried inactivating+deleting the plugin and it's folder) and created a new page, but still get the same error and the values are serialized in the database. Only way to get the non serialized way for me is to revert to 1.2.5.

Not really a problem for the project to run 1.2.5 but would be interesting to find out what could be creating this situation.

**Comment by frozzare** [comment]
I can confirm that this is a bug now. Will look into why it's saved as serialized property values.

**Comment by frozzare** [comment]
Ah, I see the problem. v1.2.6 was target against master branch, I released v1.2.7 that is target against right branch. Sorry for the problem.

https://github.com/wp-papi/papi/releases/tag/v1.2.7

**Comment by Lindstromer** [comment]
No problem, I'll update to latest. Good thing it wasn't a real bug. :+1:
