### ISSUE TITLE
[Feature] - File property

### ISSUE THREAD

**Issue by nlemoine** [wp-papi/papi#71]
Hi, 

Would you agree to add a file property (like image but will accept any type of file)?
I can work on a PR if needed.

**Comment by frozzare** [comment]
Thanks for the feature idea. A file property is something that I will add very soon, probably to next version of Papi, 2.2.0  (no due date yet). It's basically copy the image property code and make some changes and add tests.

I assume that it would be great if both `file` and `files` exists like `image` and `gallery` so you could add more then one file if needed. What do think about that @nlemoine?

**Comment by nlemoine** [comment]
I recently used papi for the first time in a project and "cheated" by using the relationship property with the `attachment` post type to make a `files` field but it would be great for sure to have both!

I have one unrelated-to-this-issue question regarding the `repeater` field. I didn't find any method like `the_papi_field` to retrieve sub fields values (maybe because I was expecting a method like `papi_get_subfield`) so I checked out the code base and found there was a way to get a specific item of an array with a javascript like syntax: `"image.url" will get the url value in the array.`
https://github.com/wp-papi/papi/blob/master/src/includes/lib/field.php#L93

Is it how you proceed to get sub properties? Something like: `slug.0.sub_slug` where `0` is dynamically replaced by the loop index?

**Comment by frozzare** [comment]
#### File

Since attachment is a post you can use `relationship` or `post` but it would be nicer to have a `file/files` instead. I will take a look at it!

#### Repeater

You could do a for loop and create `slug.0.sub_slug` with `the_papi_field`. But when you use a repeater I would use `papi_get_field` instead since it returns the array of all repeater rows. With `papi_get_field` you would get a array that looks like this:

```php
array
(
  [0] => array
  (
    [text] => 'Test 1'
    [color] => '#ffffff'
  )

  [1] => array
  (
    [text] => 'Test 2'
    [color] => '#000000'
  )
)
```

**Comment by nlemoine** [comment]
**File**

Thanks for you reply and considering the request!

**Repeater**

Yes, that's nearly what I did: 
```php
<?php if( $repeater_field = papi_get_field('slug') ): ?>
<?php foreach( $repeater_field as $i => $field ): ?>
<?php if( $img = papi_get_field('slug.' . $i . '.sub_slug') ): ?>
// img
<?php endif; ?>
<?php endforeach; ?>
<?php endif; ?>
```
I just wanted to know how you were personally dealing with this.

**Comment by frozzare** [comment]
#### Repeater

You don't need to use `papi_get_field` when you are inside a property since all sub fields already is converted to right type.

You could do it like this instead.

```php
$repeater_field = papi_get_field( 'slug' );

foreach( $repeater_field as $i => $row ) {
    if ( isset( $row['sub_slug'] ) ) {
       // do something with sub slug
    }
}
```

**Comment by nlemoine** [comment]
That's what I did at first but I was looking for a "cleaner" way to do this as I don't really like doing to much logic in templates (such checking if a key is set).

**Comment by frozzare** [comment]
Maybe you should considering to have a view file that you pass along data that should be rendered? Where you will have your logic in `page.php` and at the end it will render `views/page.php` or something like that. I do it myself with my own [twig](https://github.com/frozzare/digster) plugin.

**Comment by nlemoine** [comment]
Thanks, I will check that out! I love Twig when working in Symfony, I saw Timber and some other stuff but didn't try yet on WordPress.

**Comment by frozzare** [comment]
Added [file](https://github.com/wp-papi/papi/blob/master/src/includes/properties/class-papi-property-file.php) property and [files](https://github.com/wp-papi/papi/blob/master/src/includes/properties/class-papi-property-files.php) property. It will work as `image` property and `gallery` property. The big different is that the filename will be visible on `file` and `files` like in the media grid.

<img width="386" alt="skarmklipp 2015-07-18 16 14 40" src="https://cloud.githubusercontent.com/assets/14610/8761884/21d2d280-2d68-11e5-898d-cf9dff28ae3b.png">

It will work to add image in the file property since they are files. The `image` property will extend `file` property, `gallery` property will extend `image` property and `files` property will extend `file` property.

All four properties will existing in the next release of Papi. It's a bit work with conditional logic left before I can create a release.

**Comment by nlemoine** [comment]
Thanks a lot for considering this feature so fast! I'll watch out for the new release.
