### ISSUE TITLE
[notice] - Bulk trashing/restoring posts

### ISSUE THREAD

**Issue by nlemoine** [wp-papi/papi#75]
Bulk trashing or restoring posts (any post type) triggers a `Array to string conversion` notice in wp-includes/formatting.php on line 766. 

Do you have this too?

**Comment by frozzare** [comment]
Have you tested without Papi activated? 



Med vänlig hälsning,Fredrik

**Comment by nlemoine** [comment]
Yes, on a clean WP install. Jus tin case: I'm on Mac OS X 10.10 + PHP 5.6 (I also tested on PHP 5.4 and I'm having the same issue).

**Comment by frozzare** [comment]
Which version of Papi? Latest 2.x or master?

**Comment by nlemoine** [comment]
Happens with Latest 2.x, doesn't with master! So I'll close the issue.

**Comment by frozzare** [comment]
I can confirm this but since I will release a new Papi version next week I think the fix can wait. The problem was that `sanitize_text_field` was called with arrays, [2.x](https://github.com/wp-papi/papi/blob/2.x/src/includes/lib/utilities.php#L284) vs [master](https://github.com/wp-papi/papi/blob/master/src/includes/lib/utilities.php#L296-L298).

**Comment by nlemoine** [comment]
Thanks for the information. I've updated to master in the meantime.
